// src/data/galleryData.ts
export const galleryImages = [
  { src: "/assets/aerial-view-layout.webp", category: "Aerial View" },
  { src: "/assets/architecture-1.webp", category: "Architecture" },
  { src: "/assets/architecture-2.webp", category: "Architecture" },
  { src: "/assets/architecture-3.webp", category: "Architecture" },
  { src: "/assets/architecture-4.webp", category: "Architecture" },
  { src: "/assets/banquet-hall-amenities.webp", category: "Entertainment" },
  { src: "/assets/bedroom-interior.webp", category: "Bedroom" },
  { src: "/assets/cafe-common-area.webp", category: "Dining" },
  { src: "/assets/courts-recreation.webp", category: "Recreation" },
  { src: "/assets/entryways-1.webp", category: "Entryways" },
  { src: "/assets/entryways-main-gate.webp", category: "Entryways" },
  { src: "/assets/entryways-main-gate-2.webp", category: "Entryways" },
  { src: "/assets/exterior-main-entrance.webp", category: "Exterior" },
  { src: "/assets/exterior-main-entrance-2.webp", category: "Exterior" },
  { src: "/assets/exterior-main-entrance-3.webp", category: "Exterior" },
  { src: "/assets/exterior-villas.webp", category: "Bungalow" },
  { src: "/assets/exterior-villas-2.webp", category: "Bungalow" },
  { src: "/assets/game-room-recreation.webp", category: "Recreation" },
  { src: "/assets/game-room-recreation-2.webp", category: "Recreation" },
  { src: "/assets/gardens-pathways-1.webp", category: "Gardens" },
  { src: "/assets/gardens-pathways-2.webp", category: "Gardens" },
  { src: "/assets/gym-amenities.webp", category: "Amenities" },
  { src: "/assets/home-theater-amenities.webp", category: "Entertainment" },
  { src: "/assets/home-theater-amenities-2.webp", category: "Entertainment" },
  { src: "/assets/lobby-common-area.webp", category: "Common Areas" },
  { src: "/assets/lobby-common-area-2.webp", category: "Common Areas" },
  { src: "/assets/playground-landscapes.webp", category: "Recreation" },
  { src: "/assets/pool-wellness.webp", category: "Pool" }
];

export const categories = [
  "All",
  "Aerial View",
  "Architecture", 
  "Balcony",
  "Bedroom",
  "Bungalow",
  "Common Areas",
  "Dining",
  "Entertainment",
  "Entryways",
  "Exterior",
  "Gardens",
  "Pool",
  "Recreation"
];